### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Motzee** [Motzee/symf_mlp-api#1]
- [ ] système de check pour les données reçues en POST
- [ ] ajout dans l'entité et BDD d'une propriété/champ "avatar" servant l'url d'une image
- [ ] route d'édition (PUT ? PATCH ? à décider)
- [ ] autoriser les connexions externes, système d'identification pour l'édition de BDD ?
- [ ] Compléter la BDD ^__^
